---
version: "2.4"
services:
  postgresql:
    image: 'bitnami/postgresql:latest'
    environment:
      - POSTGRESQL_USERNAME=openhrms
      - POSTGRESQL_PASSWORD=password123
      - POSTGRESQL_DATABASE=openhrms
    networks:
      - openhrms

  app:
    image: penguintech/openhrms
    build: .
    ports:
      - 8069:8069
    networks:
      - openhrms
    healthcheck:
      test: ["CMD", "ansible-playbook", "entrypoint.yml", "--tag", "test"]
      interval: 5m
      timeout: 10s
      retries: 5
      start_period: 5s

networks:
  openhrms: